### ISSUE TITLE
[BUG] Uncaught error thrown when debugging `conduit.dart create list-templates`

### ISSUE THREAD

**Issue by MarkOSullivan94** [conduit-dart/conduit#106]
**Describe the bug**

Whenever trying to debug `conduit.dart` (`packages/conduit/bin/conduit.dart`) using IntelliJ and run it with `create list-templates` arguments I get the following stacktrace.

```text
-- Conduit CLI Version: 3.1.2
*** Uncaught error
    Bad state: No element
  **** Stacktrace
  * #0      ListMixin.firstWhere (dart:collection/list.dart:167:5)
  * #1      CLIConduitGlobal.conduitPackageRef (package:conduit/src/cli/commands/create.dart:388:10)
  * #2      CLIConduitGlobal.templateDirectory (package:conduit/src/cli/commands/create.dart:393:12)
  * #3      CLITemplateList.handle (package:conduit/src/cli/commands/create.dart:341:53)
  * #4      CLICommand.process (package:conduit/src/cli/command.dart:219:20)
  * <asynchronous suspension>
  * #5      main (file:///Users/mos/IdeaProjects/Work/conduit/packages/conduit/bin/conduit.dart:9:14)
  * <asynchronous suspension>
  ****
```

**To Reproduce**
1. Clone master 
2. Open project on IntelliJ
3. Setup run configuration to debug `conduit.dart`
4. Click button to start debugging 
5. Uncaught error will be thrown

I have not globally activated conduit so the getter for `conduitPackageRef` returns null

**Expected behavior**

I should be able to debug `conduit.dart` without errors and should conduit not have been installed globally, then the templates would be found in the cloned conduit repo.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS 12.2

**Comment by j4qfrost** [comment]
This is actually expected behavior. Currently conduit requires global activation to run. I'll work to make this not the case.

**Comment by j4qfrost** [comment]
This works fine for me, `dart run --pause-isolates-on-start --observe bin/conduit.dart create list-templates`

Reopen if you still have issues running a debugger.

**Comment by j4qfrost** [comment]
Closed by [PR #8 on j4qfrost/conduit](https://snowman.tailddc637.ts.net:8443/j4qfrost/conduit/pulls/8) (same fix as #194; private fork; not yet upstreamed).

The IntelliJ-debug case where conduit is *not* globally activated now resolves the templates dir via `Isolate.resolvePackageUri`, which traverses the running isolate's package_config and works for both checkout-debug and path-activated installs.
