### ISSUE TITLE
[BUG] NGINX reverse proxy internal error

### ISSUE THREAD

**Issue by ranierjardim** [conduit-dart/conduit#110]
**Describe the bug**
I setup a NGINX (using [SWAG Docker Hub Image](https://hub.docker.com/r/linuxserver/swag)) reverse proxy to redirect to my conduit app container, but when i request any resource using the NGNIX endpoint i get a internal error from the conduit app. If i bypass NGINX it works well as expected.

**To Reproduce**
1. Setup NGINX Reverse proxy pointing to the conduit app
2. Request the nginx server

**Expected behavior**
I think be able to work with reverse proxy

**Screenshots**
#0      _HttpHeaders.chunkedTransferEncoding= (dart:_http/http_headers.dart:187:7)
#1      _HttpHeaders._addTransferEncoding (dart:_http/http_headers.dart:386:7)
#2      _HttpHeaders._add (dart:_http/http_headers.dart:363:11)
#3      _HttpHeaders._addAll (dart:_http/http_headers.dart:74:7)
#4      _HttpHeaders.add (dart:_http/http_headers.dart:65:5)
#5      Request.respond (package:conduit/src/http/request.dart:289:24)
#6      Controller._sendResponse (package:conduit/src/http/controller.dart:329:20)
#7      Controller.receive (package:conduit/src/http/controller.dart:164:17)
<asynchronous suspension>

**Desktop (please complete the following information):**
 - OS: dart:2.17.3 (container image)
 - Browser: Chrome

**Comment by ranierjardim** [comment]
I find a solution: 
- Add the directive "**proxy_http_version 1.1;**" to your "location" config in the nginx server
