### ISSUE TITLE
`conduit build` coping package to temp path within the package cause a io error [BUG]

### ISSUE THREAD

**Issue by xaxys** [conduit-dart/conduit#138]
**Describe the bug**
On Windows platform, `conduit build` will copy whole package into a temp dir within the package path, which cause an io error.

**To Reproduce**
```
D:\Flutter\webapp1>conduit build
-- Conduit CLI Version: 3.2.10
-- Conduit project version: 3.2.10
Resolving ASTs...
Generating runtime...
Generated runtime at 'file:///D:/Flutter/webapp1//tmp/build/generated_runtime/'.
Compiling package 'conduit_runtime'...
Package 'conduit_runtime' compiled to 'file:///D:/Flutter/webapp1//tmp/build/packages/conduit_runtime/'.
Compiling package 'conduit'...
Package 'conduit' compiled to 'file:///D:/Flutter/webapp1//tmp/build/packages/conduit/'.
Compiling package 'conduit_config'...
Package 'conduit_config' compiled to 'file:///D:/Flutter/webapp1//tmp/build/packages/conduit_config/'.
Copying application package (from 'file:///D:/Flutter/webapp1/')...
*** Uncaught error
    Bad state: Invalid argument(s): Cannot copy from D:\Flutter\webapp1\ to D:\Flutter\webapp1\\tmp\build\packages\webapp1\
  **** Stacktrace
  * #0      _doNothing (package:io/src/copy_path.dart:14:5)
  * #1      copyPath (package:io/src/copy_path.dart:29:7)
  * #2      Build.copyPackage (package:conduit_runtime/src/build.dart:172:11)
  * #3      Build.execute (package:conduit_runtime/src/build.dart:83:13)
  * <asynchronous suspension>
  * #4      BuildExecutable.execute (<data:application/dart>:13:252)
  * <asynchronous suspension>
  * #5      main (<data:application/dart>:9:18)
  * <asynchronous suspension>
  ****
```

Error is raised by `dart:io/src/copy_path.dart`
```
bool _doNothing(String from, String to) {
  if (p.canonicalize(from) == p.canonicalize(to)) {
    return true;
  }
  if (p.isWithin(from, to)) {
    throw ArgumentError('Cannot copy from $from to $to');
  }
  return false;
}

/// Copies all of the files in the [from] directory to [to].
///
/// This is similar to `cp -R <from> <to>`:
/// * Symlinks are supported.
/// * Existing files are over-written, if any.
/// * If [to] is within [from], throws [ArgumentError] (an infinite operation).
/// * If [from] and [to] are canonically the same, no operation occurs.
///
/// Returns a future that completes when complete.
Future<void> copyPath(String from, String to) async
...
```

**Comment by j4qfrost** [comment]
@xaxys can you test and review this after the CI tests pass? https://github.com/conduit-dart/conduit/pull/139

**Comment by j4qfrost** [comment]
I didn't read the error carefully enough. The function doesn't copy to avoid getting stuck in an infinite loop. This had been solved in the CI. I think I have an idea about what's going on.

**Comment by j4qfrost** [comment]
@xaxys can you check one more time? I just changed the options parsing.

**Comment by xaxys** [comment]
It work well for me now. Thank you for your work.
However, I still wondering if it is a good idea to use `[Driver Letter]:\tmp` as a temporary work dir.

**Comment by xaxys** [comment]
Oh, there is another problem. The extension name of `conduit build`'s output file should be `.exe` instead of `.aot` on Windows, since it is a self-contained executable file.
Also the same in linux, no extension name should be added of `conduit build`'s output file.
