### ISSUE TITLE
[BUG] create migration file `.packages` not found

### ISSUE THREAD

**Issue by jayjah** [conduit-dart/conduit#145]
**Describe the bug**
Running command `dart pub global run conduit db generate ` causes the following error:

```
Create migration files...

Building package executable... (2.7s)
Built conduit:conduit.
-- Conduit CLI Version: 3.1.2
-- Conduit project version: 3.2.10
    Replaying versions: 1...
*** Uncaught error
    Bad state: Package file 'file:///Users/jayjah/projects/movementfamily/dart_backend/.packages' not found. Run 'pub get' and retry.
  **** Stacktrace
  * #0      IsolateExecutor.execute (package:conduit_isolate_exec/src/executor.dart:30:7)
  * #1      IsolateExecutor.run (package:conduit_isolate_exec/src/executor.dart:126:21)
  * #2      CLIDatabaseManagingCommand.schemaByApplyingMigrationSources (package:conduit/src/cli/mixins/database_managing.dart:53:45)
  * #3      CLIDatabaseGenerate.handle (package:conduit/src/cli/commands/db_generate.dart:68:26)
  * #4      CLICommand.process (package:conduit/src/cli/command.dart:219:20)
  * <asynchronous suspension>
  * #5      main (file:///Users/jayjah/.pub-cache/hosted/pub.dartlang.org/conduit-3.1.2/bin/conduit.dart:9:14)
  * <asynchronous suspension>
  ****
```

**Expected behavior**
Create migration file

**Desktop (please complete the following information):**
 - macOS arm64

**Comment by j4qfrost** [comment]
This is no longer relevant. Please upgrade to the latest version.

**Comment by j4qfrost** [comment]
You need to activate the latest version.

Conduit CLI Version: 3.1.2

I will make separating the cli from the framework a priority.
