### ISSUE TITLE
Error when build aot snapshot

### ISSUE THREAD

**Issue by zaidite** [conduit-dart/conduit#196]
Aot file building without error, but in the finish i get an error:

aot_builder  | Success. Executable is located at 'file:///app/test/test.aot'.
aot_builder  | Unhandled exception:
aot_builder  | FileSystemException: Deletion failed, path = '/tmp/build' (OS Error: Device or resource busy, errno = 16)
aot_builder  | #0      _Directory._deleteSync (dart:io/directory_impl.dart:193:7)
aot_builder  | #1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:424:7)
aot_builder  | #2      CLIBuild.cleanup (package:conduit/src/commands/build.dart:89:22)
aot_builder  | #3      CLICommand.process (package:conduit/src/command.dart:248:13)
aot_builder  | <asynchronous suspension>
aot_builder  | #4      main (file:///root/.pub-cache/hosted/pub.dev/conduit-4.3.6/bin/conduit.dart:9:14)
aot_builder  | <asynchronous suspension>
aot_builder exited with code 255

and folder which unclude in build becomes empty.

dart=2.19.2
conduit 4.3.6
mac os catalina 10.15.7

**Comment by j4qfrost** [comment]
Closed by the `conduit build` CLI being retired in favor of `dart run build_runner build && dart compile exe` (private fork; not yet upstreamed).

The `/tmp/build` cleanup that raised `FileSystemException: Deletion failed (Device or resource busy)` lived in `CLIBuild.cleanup`; that command and its supporting `BuildManager` / `BuildContext` machinery have been removed. AOT compilation now goes through `package:build_runner` and writes its outputs under your project's own `lib/` and the user-specified `dart compile exe -o` path — no `/tmp/build` lifecycle, no orphaned isolate handles.
