### ISSUE TITLE
conduit create my_project

### ISSUE THREAD

**Issue by glourencosilva** [conduit-dart/conduit#197]
conduit create my_project
Null check operator used on a null value
*** Uncaught error
    Null check operator used on a null value
  **** Stacktrace
  * #0      CLICommand.toolVersion (package:conduit/src/command.dart:115:24)
  * <asynchronous suspension>
  * #1      CLICommand.process (package:conduit/src/command.dart:228:45)
  * <asynchronous suspension>
  * #2      main (file:///home/glourenco/.pub-cache/hosted/pub.dev/conduit-4.3.9/bin/conduit.dart:9:14)
  * <asynchronous suspension>
  ****

**Comment by j4qfrost** [comment]
Can you check $PUB_CACHE/hosted/pub.dev for conduit packages?

**Comment by ArinFaraj** [comment]
I get the error, fresh install in macos

**Comment by andyhorn** [comment]
I'm getting the same error with any `conduit` command

**Comment by colbyduke** [comment]
I'm getting the same error. I checked  $PUB_CACHE/hosted/pub.dev and it has 9 folders that start with "conduit" so, I think that's good. 
What else should I check?

**Comment by alguintu** [comment]
Trying out conduit for the first time. Fresh install, `conduit --version` and `conduit create my_proj` both throw the same error :

```
Null check operator used on a null value
*** Uncaught error
    Null check operator used on a null value
  **** Stacktrace
  * #0      CLICommand.toolVersion (package:conduit/src/command.dart:115:24)
  * <asynchronous suspension>
  * #1      CLICommand.process (package:conduit/src/command.dart:223:52)
  * <asynchronous suspension>
  * #2      main (file:///C:/Users/User/AppData/Local/Pub/Cache/hosted/pub.dev/conduit-4.4.0/bin/conduit.dart:9:14)
  * <asynchronous suspension>
  ****
```

Any luck moving forward? @colbyduke @andyhorn @ArinFaraj

**Comment by ArinFaraj** [comment]
Move to [other projects](https://fluttergems.dev/web-server/). as this project is not actively maintained.

**Comment by j4qfrost** [comment]
The "No template at ." surface is fixed by [PR #8 on j4qfrost/conduit](https://snowman.tailddc637.ts.net:8443/j4qfrost/conduit/pulls/8) (private fork; not yet upstreamed).

The remaining `Null check operator on null value` at `CLICommand.toolVersion` (`command.dart:115`) is a separate code path: it reads conduit's own pubspec to determine its version, and crashes when the pubspec can't be located. If you still hit this on the latest fork, please reopen with the output of `dart pub global list` and the contents of your `~/.pub-cache/global_packages/conduit/pubspec.yaml`.
