### ISSUE TITLE
[BUG] getting below error when running db related commands

### ISSUE THREAD

**Issue by rankdhaval** [conduit-dart/conduit#232]
C:\Users\rankd\project\bnbServer>conduit db generate
-- Conduit CLI Version: 4.0.1
-- Conduit project version: 4.0.1
*** Uncaught error
    FormatException: Invalid radix-10 number (at character 1)
\Users\rankd\project\bnbServer\migrations\00000010
^

  **** Stacktrace
  * #0      int._handleFormatError (dart:core-patch/integers_patch.dart:131:5)
  * #1      int._parseRadix (dart:core-patch/integers_patch.dart:157:16)
  * #2      int._parse (dart:core-patch/integers_patch.dart:103:12)
  * #3      int.parse (dart:core-patch/integers_patch.dart:65:12)
  * #4      MigrationSource.versionNumberFromUri (package:conduit/src/cli/migration_source.dart:56:16)
  * #5      MigrationSource.versionNumber (package:conduit/src/cli/migration_source.dart:67:28)
  * #6      CLIDatabaseManagingCommand.projectMigrations.<anonymous closure> (package:conduit/src/cli/mixins/database_managing.dart:41:35)        
  * #7      Sort._dualPivotQuicksort (dart:_internal/sort.dart:96:16)
  * #8      Sort._doSort (dart:_internal/sort.dart:60:7)
  * #9      Sort.sort (dart:_internal/sort.dart:33:5)
  * #10     ListMixin.sort (dart:collection/list.dart:356:10)
  * #11     CLIDatabaseManagingCommand.projectMigrations (package:conduit/src/cli/mixins/database_managing.dart:41:15)
  * #12     CLIDatabaseGenerate.handle (package:conduit/src/cli/commands/db_generate.dart:65:9)
  * #13     CLICommand.process (package:conduit/src/cli/command.dart:235:20)
  * <asynchronous suspension>
  * #14     main (file:///C:/Users/rankd/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/conduit-4.0.1/bin/conduit.dart:9:14)
  * <asynchronous suspension>
  ****
please help me to resolve it

**Comment by j4qfrost** [comment]
**Maintainer triage 2026-04-27**: this is a real Windows-path bug. `MigrationSource.versionNumberFromUri` (`packages/cli/lib/src/migration_source.dart`) does:

```dart
final fileName = uri.pathSegments.last;
return int.parse(fileName.split('_').first);
```

On Windows, when the URI is constructed with backslashes, `pathSegments.last` returns the entire `\Users\...\migrations\00000010` path, which `int.parse` chokes on at the leading backslash. The fix is to use `path.basenameWithoutExtension(uri.toFilePath(windows: Platform.isWindows))` (or split on the last platform separator) before parsing. Welcome a PR; otherwise this stays open as a known Windows bug.
