### ISSUE TITLE
[BUG] Centos run conduit error

### ISSUE THREAD

**Issue by DizzyDuan** [conduit-dart/conduit#236]
/root/.pub-cache/bin/conduit: line 8: dart: command not found

*** Uncaught error
    Null check operator used on a null value
  **** Stacktrace
  * #0      CLICommand.toolVersion (package:conduit/src/command.dart:113:24)
  * <asynchronous suspension>
  * #1      CLICommand.process (package:conduit/src/command.dart:230:45)
  * <asynchronous suspension>
  * #2      main (file:///root/.pub-cache/hosted/pub.flutter-io.cn/conduit-5.1.3/bin/conduit.dart:9:14)
  * <asynchronous suspension>
  ****

**Comment by j4qfrost** [comment]
@DizzyDuan Can you tell me how you've installed conduit? Have you checked the github actions workflow. Those steps generally lay out the best way to install conduit. If you are running conduit via docker, everything should be set.

**Comment by DizzyDuan** [comment]
I followed the installation process in this link

https://docs.theconduit.dev/getting_started/

**Comment by j4qfrost** [comment]
The first error in your trace — `/root/.pub-cache/bin/conduit: line 8: dart: command not found` — is your shell environment: the conduit launcher script invokes `dart` and your `PATH` doesn't have it. The downstream `Null check operator used on a null value` is the framework crashing because `dart --version` failed to produce output, not the underlying bug. Add the directory containing your `dart` binary (often `/usr/lib/dart/bin`) to `PATH` and the launcher will work. Reopen welcome with a stack from a working `dart` install.
